#!/bin/sh
if [ -f ~/jenkins.war ]
then
	echo 'Found jenkins installation.'
else
	echo 'Installing jenkins.'
	wget -O ~/jenkins.war http://mirrors.jenkins-ci.org/war/latest/jenkins.war
fi
echo 'Installing dotCloud scaffolding.'
cp -a jenkins/. ~
